# Generated by Django 2.2.5 on 2020-09-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200910_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='creaated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='creaated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='houserule',
            old_name='creaated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='creaated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='creaated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='creaated',
            new_name='created',
        ),
    ]
