# Generated by Django 2.2.5 on 2020-09-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200910_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creaated',
            new_name='created',
        ),
    ]
